# Configuration of logging
version: 1
disable_existing_loggers: true
root:
    level: NOTSET
    handlers: [console]
loggers:
    core.app:
        level: INFO
        handlers: [applog]
        qualname: core.app
        propagate: false
handlers:
    applog:
        class: logging.handlers.RotatingFileHandler
        filename: ./logs/storage_app.log
        formatter: simple
        level: NOTSET
        maxBytes: 1048576  # 1MB
        backupCount: 10
        encoding: utf8
    liblog:
        class: logging.handlers.RotatingFileHandler
        filename: ./logs/storage_lib.log
        formatter: simple
        level: NOTSET
        maxBytes: 1048576  # 1MB
        backupCount: 10
        encoding: utf8
    console:
        class: logging.StreamHandler
        stream: ext://sys.stdout
        formatter: simple
        level: NOTSET
formatters:
    simple:
        class: logging.Formatter
        format: '%(asctime)s %(name)s %(levelname)s : %(message)s'
        datefmt: '%d.%m.%Y %H:%M:%S'
