# Configuration of container orchestration
version: '2'
services:
    center:
        build: ./center
        image: radiality/example-center
        container_name: example-center
        ports:
            - "50500:8888"
        volumes:
            - ./center/core:/subsystem/core
            - ./center/tests:/subsystem/tests
            - ./center/configs:/subsystem/configs
            - ./center/scripts:/subsystem/scripts
            - ./center/logs:/subsystem/logs
        cpuset: "0"
    console:
        build: ./console
        image: radiality/example-console
        container_name: example-console
        depends_on:
            - center
        ports:
            - "50900:8888"
        volumes:
            - ./console/core:/subsystem/core
            - ./console/tests:/subsystem/tests
            - ./console/configs:/subsystem/configs
            - ./console/scripts:/subsystem/scripts
            - ./console/logs:/subsystem/logs
        cpuset: "0"
    storage:
        build: ./storage
        image: radiality/example-storage
        container_name: example-storage
        depends_on:
            - center
        ports:
            - "50100:8888"
        volumes:
            - ./storage/core:/subsystem/core
            - ./storage/tests:/subsystem/tests
            - ./storage/configs:/subsystem/configs
            - ./storage/scripts:/subsystem/scripts
            - ./storage/logs:/subsystem/logs
        cpuset: "0"
